"""Initial

Revision ID: d9a5180c30e7
Revises: 
Create Date: 2023-08-04 20:54:43.121242

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d9a5180c30e7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channels",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url", sa.String(length=200), nullable=False),
        sa.Column("last_video", sa.String(length=200), nullable=True),
        sa.Column("last_stream", sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_table(
        "temp",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("telegram_id", sa.BIGINT(), nullable=False),
        sa.Column("text", sa.String(length=4096), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("telegram_id", sa.BIGINT(), nullable=False),
        sa.Column("first_name", sa.String(length=200), nullable=False),
        sa.Column("last_name", sa.String(length=200), nullable=True),
        sa.Column("add_subs_count", sa.SMALLINT(), nullable=False),
        sa.Column("auth_timestamp", sa.DateTime(), nullable=False),
        sa.Column("blocked", sa.BOOLEAN(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("telegram_id"),
    )
    op.create_table(
        "association",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BIGINT(), nullable=False),
        sa.Column("channel_id", sa.BIGINT(), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channels.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id", "user_id", "channel_id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("user_id", "channel_id", name="_user_channel_uc"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("association")
    op.drop_table("users")
    op.drop_table("temp")
    op.drop_table("channels")
    # ### end Alembic commands ###
