version: "3.8"

services:
  bot:
    container_name: yt_notif_bot_con
    image: yt_notif_bot:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./db:/db
      - ./certs:/certs
      - ./src/log/logs:/src/log/logs
    environment:
      - ENV_FILE=/src/env/prod.env
    command:
      - "python"
      - "main.py"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  nginx:
    container_name: nginx_con
    image: nginx_r_proxy:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./certs:/etc/nginx/TLS
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
    ports:
#      - "${WEBHOOK_HOST}:${WEBHOOK_PORT}:8443"
      - "8443:8443"
    depends_on:
      - bot
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
